name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: win
            arch: x86_64
            filename: MPA-win-x86_64-*.zip
          - os: win
            arch: aarch64
            filename: MPA-win-aarch64-*.zip
          - os: linux
            arch: x86_64
            filename: MPA-linux-x86_64-*.tar.gz
          - os: linux
            arch: aarch64
            filename: MPA-linux-aarch64-*.tar.gz
          - os: macos
            arch: x86_64
            filename: MPA-macos-x86_64-*.dmg
          - os: macos
            arch: aarch64
            filename: MPA-macos-aarch64-*.dmg
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ matrix.filename }}
          mirrorchyan_rid: MAA_Punish

          owner: overflow65537
          repo: MAA_Punish
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

  mirrorchyan_res:
    runs-on: macos-latest
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: MPA-win-x86_64-*.zip
          pick_files: '["resource", "interface.json", "custom"]'
          exclude_files: '["*model/ocr/**"]'
          mirrorchyan_rid: MAA_Punish

          owner: overflow65537
          repo: MAA_Punish
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
